### ISSUE TITLE
Reporting unchanged/matching in diffs

### ISSUE THREAD

**Issue by Theemim** [earthlng/FFprefs-diffs#3]
Would it be an inconvenience to you, or anyone else, if you included an unchanged/matching section in your /diffs/* files?  That way we could see all the prefs you discovered for a particular release.  I'd like to do a comparison.  The pref calls are easiest to work with, but I'd take any format.  If it isn't a bother, that is.

**Comment by earthlng** [comment]
I don't want to include matching ones in my diffs here, but I've created a special version just for you:
http://pasted.co/0fece49d/fullscreen.php?hash=8539aa0692e489e03a668ca26e9a33c3&toolbar=true&linenum=false

ps. based on the win64 en-US releases from https://ftp.mozilla.org/pub/firefox/releases/

**Comment by earthlng** [comment]
please let me know if you find anything wrong or missing in my diffs

**Comment by Theemim** [comment]
Thank you!  Results: http://dpaste.com/3JT516N.  

Edit: Needed sleep before reviewing myself.  The only ones I question are app.update.channel from channel-prefs.js and devtools.netmonitor.hiddenColumns from the *multi-line* in devtools.js.

**Comment by earthlng** [comment]
Thank you!

> The only ones I question are app.update.channel from channel-prefs.js

I'm not including that file in my diffs because it only contains a single pref with the channel name.

> and devtools.netmonitor.hiddenColumns from the multi-line in devtools.js

the regular expression I use(d) didn't catch that one - fixed now, thanks!

Thanks to your diff I also noticed that we forgot to include `extensions.webcompat.perform_ua_overrides` in the ghacks-user.js System-Addons section.

If you want to do this again for future releases, let me know and I can upload another full diff for comparison.

**Comment by Theemim** [comment]
It also helped me to improve escaping in my code.  Maybe do it again for Firefox 57 and 59, since those will be of extra importance?

**Comment by earthlng** [comment]
> Maybe do it again for Firefox 57 and 59, since those will be of extra importance?

sure, np

**Comment by Thorin-II** [comment]
!set timer -release /ESR60 +alarm@Theemin +message("ask earthling for a new diff")
